name: Test
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '12.x'
    - run: npm cit
      env:
        CI: true
